# This is a basic workflow to help you get started with Actions

name: Sync  Fork

# Controls when the action will run. 
on:
  # Triggers the workflow at 00:00 on Sunday
  schedule: 
    - cron: '0 12 1/4 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Fork Sync
        uses: tgymnich/fork-sync@v1.2.1
        with:
          -owner: alereca
          -base: master
          -head: master
